name: Linting action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # https://github.com/marketplace/actions/run-linkspector-with-reviewdog
  check-links:
    name: Run linkspector
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          fail_on_error: true
  # https://github.com/sindresorhus/awesome-lint
  awesome-lint:
    name: Awesome List lint
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run awesome-lint
        run: npx awesome-lint

